USE lab_management;

-- Insert user data
INSERT INTO Users (Email, FirstName, LastName, Password, RoleName) VALUES
('alice@example.com', 'Alice', 'Patel', 'password1', 'Client'),
('bob@example.com', 'Bob', 'Singh', 'password2', 'Client'),
('charlie@example.com', 'Charlie', 'Kim', 'password3', 'Client'),
('dana@example.com', 'Dana', 'Lopez', 'password4', 'Client'),
('evan@example.com', 'Evan', 'Zhang', 'password5', 'Client'),
('fiona@example.com', 'Fiona', 'Lee', 'password6', 'Client'),
('george@example.com', 'George', 'Tran', 'password7', 'Client'),
('hannah@example.com', 'Hannah', 'Chen', 'password8', 'Client'),
('ian@example.com', 'Ian', 'Garcia', 'password9', 'Client'),
('jade@example.com', 'Jade', 'Park', 'password10', 'Client'),
('karan@example.com', 'Karan', 'Mehta', 'staffpass1', 'Staff'),
('laura@example.com', 'Laura', 'Wong', 'staffpass2', 'Staff'),
('manuel@example.com', 'Manuel', 'Rivera', 'staffpass3', 'Staff'),
('nina@example.com', 'Nina', 'Shah', 'staffpass4', 'Staff'),
('oscar@example.com', 'Oscar', 'DSouza', 'staffpass5', 'Staff'),
('priya@example.com', 'Priya', 'Bansal', 'password11', 'Client'),
('quinn@example.com', 'Quinn', 'Yamada', 'password12', 'Client'),
('ravi@example.com', 'Ravi', 'Joshi', 'password13', 'Client'),
('sofia@example.com', 'Sofia', 'Morales', 'password14', 'Client'),
('tariq@example.com', 'Tariq', 'AlMansour', 'password15', 'Client');


-- Insert test data

INSERT INTO Tests (TestName, TestCode, SampleType, Price, EstimatedTime, TestDetails) VALUES
('Complete Blood Count', 'CBC101', 'Blood', 45.00, '1 hour', 'Measures blood cell types and counts.'),
('Lipid Panel', 'LIP202', 'Blood', 55.00, '2 hours', 'Assesses cholesterol levels.'),
('Thyroid Panel', 'THY303', 'Blood', 65.00, '1.5 hours', 'Checks thyroid hormone levels.'),
('Urinalysis', 'URA404', 'Urine', 35.00, '30 minutes', 'Examines urine content and clarity.'),
('COVID-19 PCR', 'COV505', 'Nasal Swab', 120.00, '3 hours', 'Detects active COVID-19 infection.'),
('Glucose Tolerance Test', 'GLU606', 'Blood', 40.00, '2 hours', 'Evaluates blood sugar response.'),
('Allergy Panel', 'ALL707', 'Blood', 80.00, '1 day', 'Tests common allergic reactions.'),
('Liver Function Test', 'LFT808', 'Blood', 70.00, '1 hour', 'Assesses liver enzymes and proteins.'),
('Kidney Function Test', 'KFT909', 'Blood', 65.00, '1 hour', 'Monitors kidney performance.'),
('Hemoglobin A1C', 'A1C010', 'Blood', 50.00, '45 minutes', 'Shows average blood sugar over time.'),
('HIV Test', 'HIV111', 'Blood', 60.00, '2 hours', 'Detects HIV antibodies.'),
('Pregnancy Test', 'PRG212', 'Urine', 25.00, '20 minutes', 'Checks for hCG hormone.'),
('Vitamin D Test', 'VIT313', 'Blood', 55.00, '1.5 hours', 'Measures vitamin D levels.'),
('Influenza A/B Test', 'FLU414', 'Nasal Swab', 75.00, '1 hour', 'Identifies influenza virus.'),
('Mono Test', 'MON515', 'Blood', 30.00, '1 hour', 'Screens for mononucleosis.'),
('Cholesterol Test', 'CHL616', 'Blood', 52.00, '1 hour', 'Evaluates lipid profile.'),
('Electrolyte Panel', 'ELE717', 'Blood', 58.00, '1.5 hours', 'Analyzes body salt balance.'),
('Malaria Smear', 'MAL818', 'Blood', 45.00, '3 hours', 'Detects malaria parasites.'),
('C-Reactive Protein', 'CRP919', 'Blood', 48.00, '1 hour', 'Detects inflammation in the body.'),
('Strep Test', 'STR020', 'Throat Swab', 35.00, '20 minutes', 'Identifies streptococcal bacteria.');


-- Insert Test_Results data
INSERT INTO Test_Results (ResultUnit, ResultValue, AppointmentTestMappingID) VALUES
('mg/dL', '120', 18),
('mg/dL', '98', 19),
('mg/dL', '110', 20),
('mg/dL', '102', 25),
('g/L', '88', 26),
('mmol/L', '76', 27),
('mg/dL', '99', 28),
('IU/L', '87', 29),
('ng/mL', '92', 30),
('mg/dL', '113', 31),
('mmol/L', '108', 32),
('g/L', '101', 33),
('mg/dL', '89', 34),
('ng/mL', '97', 35),
('mg/dL', '120', 36),
('IU/L', '116', 37),
('mg/dL', '121', 38),
('mg/dL', '122', 39),
('mmol/L', '118', 40),
('mg/dL', '111', 41),
('g/L', '117', 42),
('mg/dL', '114', 43),
('mg/dL', '109', 44),
('g/L', '124', 45),
('mg/dL', '125', 46),
('IU/L', '126', 47),
('mg/dL', '127', 48),
('mmol/L', '128', 49),
('ng/mL', '129', 50),
('mg/dL', '130', 51),
('IU/L', '131', 52),
('mg/dL', '132', 53),
('g/L', '133', 54),
('mg/dL', '134', 55),
('%', '135', 56),
('mg/dL', '136', 57),
('mg/dL', '137', 58),
('mmol/L', '138', 59),
('IU/L', '139', 60),
('ng/mL', '140', 61),
('mg/dL', '141', 62),
('mg/dL', '120', 69),
('mg/dL', '98', 72);

